// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx2CbwzjeSBNPXXO-MuChBt8s-17pG4UE',
    appId: '1:1075076269663:web:df3908b763e89de7fdfdea',
    messagingSenderId: '1075076269663',
    projectId: 'maze-conquest-api',
    authDomain: 'maze-conquest-api.firebaseapp.com',
    storageBucket: 'maze-conquest-api.firebasestorage.app',
    measurementId: 'G-NDQFKT8MKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIThM77kC8XP-6b9Q1TJ3qrIwWFybHO9Q',
    appId: '1:1075076269663:android:2be9dc75c759ed10fdfdea',
    messagingSenderId: '1075076269663',
    projectId: 'maze-conquest-api',
    storageBucket: 'maze-conquest-api.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Q-aK76Jtp1MXHQBbu-mY07rWqqWakcE',
    appId: '1:1075076269663:ios:c526f212f76621c4fdfdea',
    messagingSenderId: '1075076269663',
    projectId: 'maze-conquest-api',
    storageBucket: 'maze-conquest-api.firebasestorage.app',
    iosClientId: '1075076269663-q9qkn1d9otuvvunu1924qvq4hobu2g2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.mazeConquestSp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Q-aK76Jtp1MXHQBbu-mY07rWqqWakcE',
    appId: '1:1075076269663:ios:c526f212f76621c4fdfdea',
    messagingSenderId: '1075076269663',
    projectId: 'maze-conquest-api',
    storageBucket: 'maze-conquest-api.firebasestorage.app',
    iosClientId: '1075076269663-q9qkn1d9otuvvunu1924qvq4hobu2g2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.mazeConquestSp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx2CbwzjeSBNPXXO-MuChBt8s-17pG4UE',
    appId: '1:1075076269663:web:df3908b763e89de7fdfdea',
    messagingSenderId: '1075076269663',
    projectId: 'maze-conquest-api',
    authDomain: 'maze-conquest-api.firebaseapp.com',
    storageBucket: 'maze-conquest-api.firebasestorage.app',
    measurementId: 'G-NDQFKT8MKW',
  );

}